### ISSUE TITLE
add-vcs-provenance command increases the size of SARIF files substantially

### ISSUE THREAD

**Issue by dbeer1** [rvermeulen/codeql-postproc#1]
Running `codeql-postproc add-vcs-provenance` on our SARIF files seems to increase the size by 10-20%, while only a minimal size increase should be expected. It seems that the command formats and spaces out the SARIF file so the extra space is from new whitespace. Is it possible to add an option not to format, or to format in a minimal style?

**Comment by rvermeulen** [comment]
This is addressed in #2 by using a compact representation for the final SARIF file.

See release https://github.com/rvermeulen/codeql-postproc/releases/tag/v0.2.1
